/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // If you want to manually specify the sidebar and avoid auto-generated dropdowns

  // If you prefer an autogenerated sidebar from the docs folder structure without dropdowns
  // (Comment out the above `tutorialSidebar` to use this one)
  autogeneratedSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;